# Don't change this! Version used to track needed updates.
version = 1
leaderRedAura = true
reinforcementSpawnSounds = true
onlyLeaderSpawnsReinforcements = false
noLeaderFromSpawners = false
noReinforcementsFromSpawners = false